# Generated by Django 5.0.2 on 2024-02-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bookstore_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="tite",
            new_name="title",
        ),
    ]
