# Generated by Django 5.0.2 on 2024-02-25 23:20

import Bookstore_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookstore_api", "0003_shoppingcartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcartitem",
            name="user",
            field=models.ForeignKey(
                default=Bookstore_api.models.get_default_user_id,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
